"use client";

import { useMemo, useState } from "react";
import { calculateImportCost, type Fuel } from "@/domain/calculator";
import { formatRub } from "@/domain/currency";
import { LeadForm } from "@/components/lead-form";

type Props = { krwToRub: number; eurToRub: number; rateDate: string | null; isFallback: boolean };
const labels: Record<string, string> = { carPriceRub: "Стоимость автомобиля", agentFeeRub: "Услуги агента", koreaCostsRub: "Расходы в Корее", freightToVladivostokRub: "Фрахт до Владивостока", customsDutyRub: "Таможенная пошлина", customsClearanceFeeRub: "Таможенный сбор", recyclingFeeRub: "Утилизационный сбор", exciseRub: "Акциз", vatRub: "НДС", cityLogisticsRub: "Доставка по России" };

export function Calculator({ krwToRub, eurToRub, rateDate, isFallback }: Props) {
  const [priceKrw, setPrice] = useState(25_000_000); const [year, setYear] = useState(2022); const [engine, setEngine] = useState(1998); const [power, setPower] = useState(150); const [fuel, setFuel] = useState<Fuel>("petrol");
  const [agentFee, setAgentFee] = useState(0); const [koreaCosts, setKoreaCosts] = useState(0); const [freight, setFreight] = useState(0); const [cityLogistics, setCityLogistics] = useState(0);
  const result = useMemo(() => {
    try { return { value: calculateImportCost({ priceKrw, krwToRub, eurToRub, ageYears: Math.max(0, new Date().getFullYear() - year), engineCc: engine, powerHp: power, fuel, agentFeeRub: agentFee, koreaCostsRub: koreaCosts, freightToVladivostokRub: freight, cityLogisticsRub: cityLogistics }), error: "" }; }
    catch (error) { return { value: null, error: error instanceof Error ? error.message : "Расчёт недоступен" }; }
  }, [priceKrw, year, engine, power, fuel, agentFee, koreaCosts, freight, cityLogistics, krwToRub, eurToRub]);
  return <div className="calculator-shell">
    <div className="calculator-fields"><label>Цена в Корее, ₩<input type="number" min="0" step="100000" value={priceKrw} onChange={(e) => setPrice(Number(e.target.value))} /><strong className="rub-preview">≈ {formatRub(priceKrw * krwToRub)}</strong><small>По курсу {krwToRub.toLocaleString("ru-RU", { maximumFractionDigits: 5 })} ₽ за ₩</small></label><label>Год выпуска<input type="number" min="2000" max={new Date().getFullYear()} value={year} onChange={(e) => setYear(Number(e.target.value))} /></label><label>Объём двигателя, см³<input type="number" min="0" max="8000" value={engine} onChange={(e) => setEngine(Number(e.target.value))} /></label><label>Мощность, л.с.<input type="number" min="1" max="1000" value={power} onChange={(e) => setPower(Number(e.target.value))} /></label><label>Тип двигателя<select value={fuel} onChange={(e) => setFuel(e.target.value as Fuel)}><option value="petrol">Бензин</option><option value="diesel">Дизель</option><option value="hybrid">Гибрид</option><option value="electric">Электро</option></select></label><label>Услуги агента, ₽<input type="number" min="0" step="10000" value={agentFee} onChange={(e) => setAgentFee(Number(e.target.value))} /></label><label>Расходы в Корее, ₽<input type="number" min="0" step="10000" value={koreaCosts} onChange={(e) => setKoreaCosts(Number(e.target.value))} /></label><label>Фрахт до Владивостока, ₽<input type="number" min="0" step="10000" value={freight} onChange={(e) => setFreight(Number(e.target.value))} /></label><label>Доставка по России, ₽<input type="number" min="0" step="10000" value={cityLogistics} onChange={(e) => setCityLogistics(Number(e.target.value))} /><small>Введите только подтверждённые суммы из предложения агента или перевозчика.</small></label></div>
    <div className="calculator-result"><p className="eyebrow">Предварительный расчёт</p>{result.value ? <><p className="total">{formatRub(result.value.totalRub)}</p><dl>{Object.entries(result.value.lines).map(([key, value]) => <div key={key}><dt>{labels[key]}</dt><dd>{formatRub(value)}</dd></div>)}</dl><p className="calculator-note">{result.value.note} Нулевые сервисные и логистические строки не включены в итог до ввода подтверждённой суммы.</p><LeadForm formId="calculator" compact calculationRub={result.value.totalRub} /></> : <div className="calculation-error"><h2>Нужен индивидуальный расчёт</h2><p>{result.error}. Оставьте заявку — менеджер проверит действующий коэффициент.</p><LeadForm formId="calculator-special" compact /></div>}{isFallback && <p className="rate-warning">В локальной сборке используется резервный курс. После подключения базы курс обновляется по ЦБ РФ.{rateDate ? ` Дата: ${rateDate}.` : ""}</p>}</div>
  </div>;
}
